services:
  - type: web
    name: nexus-api
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: MODEL_DIR
        value: /tmp/nexus_models
      - key: TELEGRAM_BOT_TOKEN
        value: 8671206037:AAFOcpT71VPWlpnOZSsto7doQx_3nsJ6qSw
      - key: TELEGRAM_CHAT_ID
        value: "8772577755"
      - key: NEWS_API_KEY
        value: e4d6d9a600bf4959af2a21aa42f225c7
      - key: ALPHA_VANTAGE_KEY
        value: SZCZ08C09V816LQH
      - key: ENVIRONMENT
        value: production

databases:
  - name: nexus-db
    plan: free
    databaseName: nexus
    user: nexus_user
